### ISSUE TITLE
College数据集运行fastlio失败

### ISSUE THREAD

**Issue by jiangpin-legend** [PengYu-Team/S3E#15]
您好，感谢分享数据集！我参照config中三个机器人的内参外参文件进行计算并对fastlio中的配置文件进行了设置，并对college数据集使用fastlio生成里程结果。

* 运行时Alpha机器人在800s左右出现了里程计漂移
![image](https://github.com/PengYu-Team/S3E/assets/60228505/12301a13-0042-4d78-98c7-47d57c0120e9)
对应参数文件如下
```yaml
#velodyne_alpha.yaml
common:
    lid_topic:  "/Alpha/velodyne_points"
    imu_topic:  "/Alpha/imu/data"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2

mapping:
    acc_cov: 1.0919628856399554e-02
    gyr_cov: 1.0451440924866223e-02
    b_acc_cov: 2.1851827629113259e-04
    b_gyr_cov: 8.1770009351257180e-05 

    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,


    extrinsic_T: [ 0.0103, -0.0443, 0.1395]
    extrinsic_R: [1, 0.0097, -0.008,
                  -0.0097, 0.9995, -0.0315,
                  0.0005, 0.0315, 0.9995]


        
        

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

```
对应的launch文件
```yaml
<launch>
  <!-- Launch file for velodyne16 VLP-16 LiDAR -->

  <arg name="rviz" default="true" />

  <!-- <rosparam command="load" file="$(find fast_lio)/config/simulation_velodyne.yaml" /> -->
  <rosparam command="load" file="$(find fast_lio)/config/velodyne_alpha.yaml" />
  <param name="RobotId" type="int" value="1" />
  <param name="dist" type="double" value="1" />
  <param name="feature_extract_enable" type="bool" value="1"/>
  <param name="point_filter_num" type="int" value="4"/>
  <param name="max_iteration" type="int" value="3" />
  <param name="filter_size_surf" type="double" value="0.5" />
  <param name="filter_size_map" type="double" value="0.5" />
  <param name="cube_side_length" type="double" value="1000" />
  <param name="runtime_pos_log_enable" type="bool" value="0" />
  <node pkg="fast_lio" type="fastlio_mapping" name="laserMappingAlpha" output="screen" /> 

  <group if="$(arg rviz)">
  <node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz_alpha" args="-d $(find fast_lio)/rviz_cfg/loam_livox.rviz" />
  </group>


</launch>

```
* 运行时Bob机器人在240s时出现了里程计漂移，后续里程计发散
![image](https://github.com/PengYu-Team/S3E/assets/60228505/084e4c7c-c1ad-43c3-a8ec-e25097de1d03)
对应的参数文件如下
```yaml
#velodyne_bob.yaml
common:
    lid_topic:  "/Bob/velodyne_points"
    imu_topic:  "/Bob/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2

mapping:
    acc_cov: 1.0557715622632996e-02
    gyr_cov: 1.0084886221461694e-02
    b_acc_cov: 2.3084619195565281e-04
    b_gyr_cov: 9.8778648600726277e-05
    
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  false     # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ 0.0139, -0.0464, 0.0903]
    extrinsic_R: 
               [ 0.9998   ,  0.0174  , -0.0051,   
                -0.0174   ,  0.9998   ,-0.0109,   
                0.0049    , 0.0109    ,0.9999,  ]

   
        

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

```

对应的launch文件
``` yaml
<launch>
  <!-- Launch file for velodyne16 VLP-16 LiDAR -->

    <arg name="rviz" default="true" />


    <rosparam command="load" file="$(find fast_lio)/config/velodyne_bob.yaml" />
    <param name="RobotId" type="int" value="2" />
    <param name="dist" type="double" value="1" />
    <param name="feature_extract_enable" type="bool" value="1"/>
    <param name="point_filter_num" type="int" value="4"/>
    <param name="max_iteration" type="int" value="3" />
    <param name="filter_size_surf" type="double" value="0.5" />
    <param name="filter_size_map" type="double" value="0.5" />
    <param name="cube_side_length" type="double" value="1000" />
    <param name="runtime_pos_log_enable" type="bool" value="0" />
    <node pkg="fast_lio" type="fastlio_mapping" name="laserMappingBob" output="screen" /> 

    <group if="$(arg rviz)">
    <node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz_bob" args="-d $(find fast_lio)/rviz_cfg/loam_livox_Bob.rviz" />
    </group>

    <!-- <node pkg="tf" type="static_transform_publisher" name="tf222" args="0 0 0 0 0 0 1 robot_1/odom /robot_1/odom 100" /> -->

</launch>

```

是否可以麻烦您提供一份测试数据集时的fastlio配置文件，感谢！
